package_assets: on
gzip_assets: off
javascript_compressor: closure

javascripts:
    defaults:
        - public/javascripts/prototype.js
        - public/javascripts/rails.js
        - public/javascripts/effects.js
        - public/javascripts/dragdrop.js
        - public/javascripts/controls.js
        - public/javascripts/jquery-1.7.0.min.js
        - public/javascripts/bootstrap.min.js
        - public/javascripts/sfapp.js
        - public/javascripts/application.js
    widget:
        - public/javascripts/underscore-1.1.6.js
        - public/javascripts/widget.js
        - app/views/widgets/*.jst
    # Widget configuration tools
    widget_config:
        - public/javascripts/underscore-1.1.6.js
        - app/views/widgets/*.jst
        - public/javascripts/widget.js
        - public/javascripts/jscolor.js
        - public/javascripts/json2.js
        - public/javascripts/widget.config.js
    common:
        - public/javascripts/jquery.buildr.js
        - public/javascripts/jquery.formatCurrency-1.4.0.min.js
        - public/javascripts/jquery.form.min.js
        - public/javascripts/jquery.qtip-1.0.0-rc3.min.js
        - public/javascripts/jquery.simplyCountable.js
        - public/javascripts/jqmodal.js
        - public/javascripts/star-rating/jquery.MetaData.js
        - public/javascripts/star-rating/jquery.rating.js
        - public/javascripts/slider.js
        - public/javascripts/sorttable.js
        - public/javascripts/builder.js
        - public/javascripts/m.js
        - public/javascripts/styles.js
    frontpage:
        - public/javascripts/jquery.jcarousel.js
        - public/javascripts/frontpage.js
    distmap:
        - public/javascripts/gmap-wms.js
        - public/javascripts/distmap.js

stylesheets:
    widgets:
        - public/stylesheets/960.css
        - public/stylesheets/reset.css
        - public/stylesheets/classes.css
        - public/stylesheets/reset.css
        - public/stylesheets/typo.css
        - public/stylesheets/master.css
        - public/stylesheets/widget.css
    application:
        - public/stylesheets/960.css
        - public/stylesheets/classes.css
        - public/stylesheets/modal.css
        - public/stylesheets/reset.css
        - public/stylesheets/typo.css
        - public/stylesheets/master.css
        - public/stylesheets/jqModal.css
        - public/stylesheets/jquery.rating.css
        - public/stylesheets/bootstrap-custom.min.css
        - public/stylesheets/kludge.css
    frontpage:
        - public/stylesheets/960.css
        - public/stylesheets/classes.css
        - public/stylesheets/modal.css
        - public/stylesheets/reset.css
        - public/stylesheets/typo.css
        - public/stylesheets/master.css
        - public/stylesheets/home.css
        - public/stylesheets/jqModal.css
        - public/stylesheets/jquery.jcarousel.css
        - public/stylesheets/search.css
        - public/stylesheets/bootstrap-custom.min.css
        - public/stylesheets/interim_index.css
        - public/stylesheets/kludge.css
    districts:
        - public/stylesheets/states.css
        - public/stylesheets/districts.css
