defaults: &defaults
  <%= "app_id: #{ApiKeys.facebook_app_id} " %>
  <%= "secret: #{ApiKeys.facebook_secret}" %>
  <%= "api_key: #{ApiKeys.facebook_api_key}" %>
  <%= "callback_url: #{Settings.facebook_callback_url}" %>

development:
  <<: *defaults

staging:
  <<: *defaults

production:
  <<: *defaults

test:
  app_id: xxx
  secret: xxx
  api_key: xxx
  callback_url: xxx

